version: '3.7'

services:
  mongo:
    image: mongo:4.2.23
    ports:
      - "27017:27017"
    volumes:
      - ./dbdata:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password

  redis:
    image: redis:5.0.7
    ports:
      - "6379:6379"
    restart: always
